# Generated by Django 5.0.1 on 2024-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_dns", "0001_squashed_netbox_dns_0_22"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="registrar",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
