# Generated by Django 5.0.7 on 2024-08-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0006_templating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ("fqdn", "zone", "name", "type", "value", "status")},
        ),
        migrations.AlterModelOptions(
            name="recordtemplate",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="zonetemplate",
            options={"ordering": ("name",)},
        ),
    ]
