# Generated by Django 5.0.9 on 2024-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0009_rename_contact_registrationcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="ip_address_filter",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
