# Generated by Django 5.1.5 on 2025-02-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0012_natural_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonetemplate",
            name="soa_mname",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="netbox_dns.nameserver",
            ),
        ),
        migrations.AddField(
            model_name="zonetemplate",
            name="soa_rname",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
