# Generated by Django 5.1.6 on 2025-02-27 19:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0122_charfield_null_choices"),
        ("netbox_dns", "0013_zonetemplate_soa_mname_zonetemplate_soa_rname"),
        ("tenancy", "0017_natural_ordering"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="zone",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="nameserver",
            name="name",
            field=models.CharField(db_collation="natural_sort", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="nameserver",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="name_unique_ci",
                violation_error_message="There is already a nameserver with this name",
            ),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("view"),
                name="name_view_unique_ci",
                violation_error_message="There is already a zone with the same name in this view",
            ),
        ),
    ]
