# Generated by Django 5.1.7 on 2025-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0015_dnssec"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnssecpolicy",
            name="status",
            field=models.CharField(default="active"),
        ),
    ]
