# Generated by Django 5.1.7 on 2025-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0017_dnssec_policy_zone_zone_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="domain_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
