# Generated by Django 5.2 on 2025-04-22 18:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0018_zone_domain_status_zone_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnssecpolicy",
            name="parental_agents",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.GenericIPAddressField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
