# Generated by Django 5.2 on 2025-05-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0020_remove_dnssecpolicy_parental_agents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="ptr_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="address_records",
                to="netbox_dns.record",
            ),
        ),
    ]
