# Generated by Django 5.2.1 on 2025-05-19 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0081_remove_service_device_virtual_machine_add_parent_gfk_index"),
        ("netbox_dns", "0021_alter_record_ptr_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="ipam_ip_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="netbox_dns_records",
                to="ipam.ipaddress",
            ),
        ),
    ]
