# Generated by Django 4.1.9 on 2023-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_dns", "0022_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="value",
            field=models.CharField(max_length=65535),
        ),
    ]
