# Generated by Django 5.2.3 on 2025-07-30 18:54

from django.db import migrations

from netbox_dns.choices import RecordTypeChoices


def set_disable_ptr_false(apps, schema_editor):
    Record = apps.get_model("netbox_dns", "Record")

    for record in Record.objects.exclude(
        type__in=(RecordTypeChoices.A, RecordTypeChoices.AAAA)
    ):
        if record.disable_ptr:
            record.disable_ptr = False
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0022_alter_record_ipam_ip_address"),
    ]

    operations = [
        migrations.RunPython(set_disable_ptr_false),
    ]
