# Generated by Django 5.2.5 on 2025-09-02 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0023_disable_ptr_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonetemplate",
            name="parental_agents",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.GenericIPAddressField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
