# Generated by Django 5.2.6 on 2025-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0024_zonetemplate_parental_agents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zone",
            name="inline_signing",
        ),
        migrations.AddField(
            model_name="dnssecpolicy",
            name="inline_signing",
            field=models.BooleanField(default=True),
        ),
    ]
