# Generated by Django 5.2.6 on 2025-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0025_remove_zone_inline_signing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnssecpolicy",
            name="nsec3_opt_out",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
