# Generated by Django 4.2.5 on 2023-10-11 09:07

from django.db import migrations, models
import django.db.models.deletion
from ipam.models import IPAddress
from django.contrib.contenttypes.models import ContentType
from extras.models import CustomField


def remove_ipam_coupling_cf_dns_record(apps, schema_editor):
    ipaddress_object_type = ContentType.objects.get_for_model(IPAddress)
    CustomField.objects.get(
        name="dns_record", content_types=ipaddress_object_type
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0067_ipaddress_index_host"),
        ("netbox_dns", "0025_ipam_coupling_cf"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="ipam_ip_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="netbox_dns_records",
                to="ipam.ipaddress",
            ),
        ),
        migrations.RunPython(remove_ipam_coupling_cf_dns_record),
    ]
