# Generated by Django 5.2.7 on 2025-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0026_alter_dnssecpolicy_nsec3_opt_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
