# Generated by Django 5.2.8 on 2025-11-12 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0028_alter_zone_default_ttl_alter_zone_soa_minimum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="ttl",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(2147483647)],
            ),
        ),
        migrations.AlterField(
            model_name="recordtemplate",
            name="ttl",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(2147483647)],
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="default_ttl",
            field=models.PositiveIntegerField(
                blank=True,
                validators=[django.core.validators.MaxValueValidator(2147483647)],
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="soa_minimum",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(2147483647)]
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="soa_ttl",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(2147483647)]
            ),
        ),
    ]
