# Generated by Django 4.2.7 on 2023-12-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_dns", "0028_zone_rfc2317_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="rfc2317_cname_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rfc2317_ptr_record",
                to="netbox_dns.record",
            ),
        ),
    ]
