# Generated by Django 5.2.9 on 2026-01-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dns", "0028_alter_zone_default_ttl_alter_zone_soa_minimum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationcontact",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
